
package nz.co.senanque.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://serverimpl.ws.senanque.co.nz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverse", targetNamespace = "http://serverimpl.ws.senanque.co.nz/", className = "nz.co.senanque.ws.server.Reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "http://serverimpl.ws.senanque.co.nz/", className = "nz.co.senanque.ws.server.ReverseResponse")
    public String reverse(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
