
package nz.co.senanque.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MyServiceImplService", targetNamespace = "http://serverimpl.ws.senanque.co.nz/", wsdlLocation = "http://localhost:8080/WS/MyService?wsdl")
public class MyServiceImplService
    extends Service
{

    private final static URL MYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(nz.co.senanque.ws.server.MyServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = nz.co.senanque.ws.server.MyServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WS/MyService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WS/MyService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MyServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceImplService() {
        super(MYSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://serverimpl.ws.senanque.co.nz/", "MyServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceImplPort")
    public MyService getMyServiceImplPort() {
        return super.getPort(new QName("http://serverimpl.ws.senanque.co.nz/", "MyServiceImplPort"), MyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServiceImplPort")
    public MyService getMyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.senanque.co.nz/", "MyServiceImplPort"), MyService.class, features);
    }

}
