# Pull base image
From tomcat:8-jre8

# Maintainer
MAINTAINER "Roger Parkinson <roger.parkinson35@gmail.com">

# Copy to images tomcat path
ADD target/madura-workflow-ui*.war /usr/local/tomcat/webapps/