# Pull base image
From tomcat:8-jre8

# Maintainer
MAINTAINER "Roger Parkinson <roger.parkinson35@gmail.com">

# Copy to images tomcat path removing version because it messes up the url
ADD target/madura-workflow-impl*.war /usr/local/tomcat/webapps/madura-workflow-impl